services:
  nginx:
    container_name: nginx-edge
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      - ui
      - service
  ui:
    container_name: nginx-ui
    build: ./ui
    ports:
      - "3000:3000"
  service:
    container_name: service
    build: ./service
    ports:
      - "8081:8081"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  nginx-cache:
